### PR TITLE
Added product menu, improved sidebar

### PR DESCRIPTION
**Pull request by alexey0975**

### CODE REVIEW

**Comment by antonkhrit** [comment]
@alexey0975 

**Sidebar comments**

Sometimes chevron icon is displayed for items that can't be expanded. Example: 
image

Probably because Sphinx detects table of contents inside the page. 

The scroll should be styled as in Figma:
image

Seach input should be styled the same way as in Figma:
image

Breadcrumps and header should be positioned as in Figma:
image

Sometimes current item gets lost in the sidebar navigation. Check this video:
https://www.screencast.com/t/24tS2mSf

Remove animation from chevrone. It looks weird when navigating between pages:
https://www.screencast.com/t/85Khz7lE2okj

**Comment by alexey0975** [comment]
@antonkhrit 
I can't reproduce the case where the chevron icon is shown where it shouldn't be. Can you send an example of the layout of this case so that I can figure out why this is happening.
image

I figured out why sometimes the current element gets lost in the sidebar. The fact is that when build, some files do not fall into the "TOC tree". This information can be seen in the warnings:
image

It looks like the builder goes through the .rst files from top to bottom alphabetically, and documents that are not included in the toc tree still affect the final result and rewrite the navigation.
To verify this, I conducted an experiment in which I renamed `/source/how-toc/index-process-pdf.rst` to `/source/how-toc/0-index-process-pdf.rst` file and re-ran the build. It is important to remove the old build before doing this and everything worked out.
image

**Comment by antonkhrit** [comment]
@alexey0975 Here is the screenshot. I'm still able to reproduce chevrone inside Zapier article:
image

About not including some articles in toctree. I will research it and get back to you.

**Comment by antonkhrit** [comment]
@alexey0975 Sometimes in documentation content is wider than screen because of tables. It is rare but sometimes it happens. 

Top navigation looks weird for cases like this. Check this link as example:
https://plumsail.com/docs/documents/v1.x/document-generation/docx/demos.html

image

**Comment by antonkhrit** [comment]
@alexey0975 please return the breadcrumbs separators back. @cherinaa added them like this into Figma not intentionally. 

I fixed it in Figma.

image

**Comment by antonkhrit** [comment]
@alexey0975 Scroll should have corners rounded. Check Figmal:
image

**Comment by antonkhrit** [comment]
@alexey0975 Search icon should remain inside input while typing. Like this:
image

But it is like this now:
image
image

**Comment by antonkhrit** [comment]
@alexey0975 давай ещё зарезервируем место для верхней навигации до её загрузки. А то сейчас из за того что она не сразу рендерится контент прыгает. Это уже сейчас плохо смотрится а с динамическим раскрытием левой навигации вообще печально будет. 

Посмотри видео чтобы понять о чём я. 
https://www.screencast.com/t/zrdssPHX2g

**Comment by antonkhrit** [comment]
@alexey0975 I pushed some content changes. Pull them to your local repo.

**Comment by alexey0975** [comment]
In the case where the content is wider than the screen, the content overflowed the block due to long lines in the template data examples:
image
To avoid this, I just added a property 'overflow: hidden;' to the parent block.

**Comment by antonkhrit** [comment]
@alexey0975 I saw you removed the horizontal scroll from the documentation. However, it breaks some other parts of docs. For example:
/document-generation/common-docx-xlsx/formatters.html

Tables are trimmed:
image

Keep your changes but add horizontal scrolls to tables. Like this:
image

**Comment by antonkhrit** [comment]
@alexey0975 disregard my previous message about the table horizontal scroll. I added it myself.

**Pull request merged**
